#!/usr/bin/env bash

docker-compose up -d --build


docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=schema-secret],SCRAM-SHA-512=[password=schema-secret]' --entity-type users --entity-name schema

docker-compose exec kafka kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --cluster --operation=All --allow-principal=User:kafka

docker-compose exec kafka kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add \
               --allow-principal 'User:schema' --allow-host '*' \
               --operation All --topic _schemas  --group 'schema-registry'
